### ISSUE TITLE
setup customColors

### ISSUE THREAD

**Issue by molot1989** [swimlane/ngx-charts#269] opened 2017-03-06 12:28 UTC
Hi, thanks for library, can you explain how use "customColors" ?

**Comment by marjan-georgiev** [comment] 2017-03-06 13:36
This was fixed in 4.2.1.

To use customColors, you need to define an array of `{name, value}` pairs, where name is the name of the item which color you want to change, and the value is the color.

Example, to change the color of 'France' to blue:
```
customColors = [
    { 
      name: 'france',
      value: '#0000ff'
    }
];
```

Here is a plunkr example which overrides the color for the value 'France'

https://plnkr.co/edit/eoP4ywMWBDWrN7OX1fKO?p=preview

**Closed** 2017-03-06 13:36 UTC

**Comment by molot1989** [comment] 2017-03-06 15:34
Thanks for example

**Comment by molot1989** [comment] 2017-03-07 10:41
It's not working for me, with multi data in "Grouped Vertical Bar Chart"
See plunkrer  
https://plnkr.co/edit/jAGau7LTa2S3ZevNt5Ed?p=preview

**Comment by marjan-georgiev** [comment] 2017-03-07 10:44
You are passing it a wrong format.

Here's a fixed plunkr:
https://plnkr.co/edit/vjhbLiGYcnr7UcAbpGWT?p=preview

**Comment by molot1989** [comment] 2017-03-07 10:54
Thanks for quick answer, but I want change color only for one country and one year. How it make?

**Comment by marjan-georgiev** [comment] 2017-03-07 10:55
You can not do that. In your case, the countries are the groups, and the bars represent the years. You can only change the colors of the years.

**Comment by molot1989** [comment] 2017-03-07 11:02
I understood, thanks for the reply

**Comment by chcald** [comment] 2017-09-26 13:36
I am the same problem

**Comment by chcald** [comment] 2017-09-26 13:37
I need to change only one.

**Comment by ssipaulya** [comment] 2018-04-16 09:53
@marjan-georgiev Above plunker is not working for me.Getting System JS error while spinning it out.
 I tried the way you have told in local copy for Heat map charts, but it is not working for me.

**Comment by frankdavidcorona** [comment] 2018-08-08 14:00
@marjan-georgiev @molot1989 https://stackoverflow.com/questions/51748555/custom-color-for-specific-serie-using-ngx-charts I need help with this.

**Comment by georgeedwards** [comment] 2018-12-30 21:40
@marjan-georgiev Thanks for this, and how about the format for passing in a function? 

The docs say this property will accept a function or object. Are there any examples of this?

**Comment by yuvalbl** [comment] 2019-03-16 22:36
Please include this explanation in the docs
Great library by the way :)

**Comment by snowPu** [comment] 2019-03-20 14:04
Does customColors not work on ngx-charts-bubble-chart? The following doesn't work.

```
 <ngx-charts-bubble-chart *ngIf="data && data.length > 0" [scheme]="colorScheme" [customColors]="customColors" [results]="data" [xAxis]="true"
      [yAxis]="true" [legend]="true" [showXAxisLabel]="true" [showYAxisLabel]="true"
      xAxisLabel="Year, Quarter" yAxisLabel="No idea">
    </ngx-charts-bubble-chart>

```

```
customColors = [
{name: 'ABC', value: '#f58c14'},
{name: 'XYZ', value: '#becdd7'}
];

data = [
{name: "Funnel Report",
series: [
	{name: 'ABC', x: 1, y: 2, r: 23},
	{name: 'XYZ', x: 3, y: 4, r: 13}
]}
];

```

**Comment by NareshKumarM** [comment] 2019-03-28 05:15
Does the library have a functionality for bar graphs where if value is negative, we can set a color of choice and vice versa?

**Comment by slwzero** [comment] 2019-04-12 02:56
> It's not working for me, with multi data in "Grouped Vertical Bar Chart"
> See plunkrer
> https://plnkr.co/edit/jAGau7LTa2S3ZevNt5Ed?p=preview

Did you solve this of  multi? I was searching this solution too.

**Comment by DavidStreid** [comment] 2019-05-21 11:22
@snowPu it looks like customColors is determined by the object name in data. In your case, "Funnel Report"

**Comment by karocksjoelee** [comment] 2019-09-26 11:57
Any one facing that if I change the custom color array dynamically will cause that the animation of the chart render extremely slow ?

**Comment by ki2itoPro** [comment] 2019-10-07 14:22
> Any one facing that if I change the custom color array dynamically will cause that the animation of the chart render extremely slow ?

Same issue for me, chart is extremely slow when I change color dynamically

**Comment by NareshKumarM** [comment] 2019-10-07 21:47
@ki2itoPro @karocksjoelee If you guys can put in a stackblitz to reproduce the issue, I can have a look at it to suggest possible fixes as I had performed the same on a larger dataset.

**Comment by btxtiger** [comment] 2020-05-18 15:24
```
customColors = [
    { 
      name: 'france',
      value: '#0000ff'
    }
];
`
``

seems not to work anymore for line charts

**Comment by btxtiger** [comment] 2020-05-19 11:09
It turned out, it is now required to pass a function:
```ts
   public getNamedColor = (statName: string) => {
      switch (statName) {
         case 'Rate of change':
            return '#31badb';
         case 'Trend':
            return '#D33F93';
         case 'Average':
            return '#9fa1a9';
         case 'Total':
            return '#CECB62';
         default:
            return '#1f3165';
      }
   };
`
``

**Comment by Adamicov** [comment] 2020-06-21 20:42
thx @btxtiger

**Comment by umbe1987** [comment] 2020-10-07 08:42
@btxtiger 

> It turned out, it is now required to pass a function:

Actually it can accept both an object or a function (as per [the docs](https://swimlane.gitbook.io/ngx-charts/examples/bar-charts/vertical-bar-chart)).

I had [a similar problem](https://github.com/swimlane/ngx-charts/issues/1526) and I have a working solution showing how to change the color of a bar upon selecting it using `customColors` poperty with and object.

Link to example: https://stackblitz.com/edit/vertical-bar-chart-atxxvq

Hope it helps ;)

**Comment by weirdyang** [comment] 2021-06-07 07:25
I can't seem to get this to work for the gauge chart.

**Comment by malabuyocfritz1984** [comment] 2023-03-25 19:38
why the documentation does not state this?
