### ISSUE TITLE
Error on gauge when disable Axis and mouse leave

### ISSUE THREAD

**Issue by emeric0101** [swimlane/ngx-charts#542] opened 2017-09-07 16:18 UTC
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
On a Gauge, when I disable Axis, if a put the mouse on the gauge value then the mouse leaves the gauge, I get this error : 

ERROR ReferenceError: event is not defined
Trace de la pile :
./src/gauge/gauge.component.ts/GaugeComponent</GaugeComponent.prototype.onDeactivate@http://localhost:4200/vendor.bundle.js:13730:32
View_GaugeComponent_1/<@ng:///GaugeModule/GaugeComponent.ngfactory.js:23:23
handleEvent@http://localhost:4200/vendor.bundle.js:109717:98
callWithDebugContext@http://localhost:4200/vendor.bundle.js:111178:39
debugHandleEvent@http://localhost:4200/vendor.bundle.js:110766:12
dispatchEvent@http://localhost:4200/vendor.bundle.js:106310:12

**Expected behavior**
Nothing but no bug

**Reproduction of the problem**
Some issue with Plücker but here is a sample (only check the app.ts) : http://plnkr.co/edit/b8lMjFnLbzcgR3M8PyTw?p=preview

**Please tell us about your environment:**
Windows 10, Atom, NPM, Ng serve

* **ngx-charts version:** 6.0.2

* **Angular version:** 4.3.6

* **Browser:** [ Firefox 55.0.3 ]

* **Language:** [TypeScript 2.3 ES6]

Thank you

**Comment by ng** [comment] 2017-09-07 16:48
Unsubscribe

**Comment by emeric254** [comment] 2018-05-02 14:04
Can't reproduce it anymore since release 7.0.0 (https://github.com/swimlane/ngx-charts/blob/master/docs/changelog.md#700)
was related to PR #613

**Comment by marjan-georgiev** [comment] 2018-05-02 14:25
Thanks for checking @emeric0101 
Closing the issue.

**Closed by marjan-georgiev** 2018-05-02 14:25 UTC
Labels: Accept PRs, Backlog, Bug, Investigate
