### ISSUE TITLE
Line Chart is not showing tooltip in IE 11

### ISSUE THREAD

**Issue by sachinshahi** [swimlane/ngx-charts#787] opened 2018-03-29 14:09 UTC
https://swimlane.github.io/ngx-charts/#/ngx-charts/line-chart

The linechart demo is not showing tooltip in IE 11

**Comment by marjan-georgiev** [comment] 2018-04-08 20:37
Closing as it is duplicate of #384

**Closed by marjan-georgiev** 2018-04-08 20:37 UTC
