### ISSUE TITLE
AOT Error with AreaChart

### ISSUE THREAD

**Issue by tomasisby** [swimlane/ngx-charts#245] opened 2017-02-24 13:32 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When aot compiling the component, it gets an error:
Error at D:/Dev/storm-admin-angular/aot/node_modules/@swimlane/ngx-charts/release/area-chart/area-chart.component.ngfactory.ts:1080:35: Supplied par
ameters do not match any signature of call target.

area-chart.component.ts:
      (legendLabelClick)="onClick($event)" 

**Expected behavior**
legendLabelClick needs two parameters: data, series

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Win

* **ngx-charts version:** x.x.x
4.1.3

* **Angular version:** 2.x.x
2.4.7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by HitomiTenshi** [comment] 2017-02-24 13:41
Duplicate of #232

**Comment by marjan-georgiev** [comment] 2017-02-24 15:02
Yup, closing this as it's a duplicate.

**Closed by marjan-georgiev** 2017-02-24 15:02 UTC
