### ISSUE TITLE
RTL issue on pie chart and polar chart labels

### ISSUE THREAD

**Issue by nileshbhagwat** [swimlane/ngx-charts#1161] opened 2019-05-09 04:37 UTC
**Describe the bug**
In RTL, Labels are not visible properly for Pie chart and polar chart

**To Reproduce**
1. Go to 'https://swimlane.github.io/ngx-charts/#/ngx-charts/pie-chart'
2. Add dir="rtl" on html tag 
3. Check labels 

**Expected behavior**
Labels should be visible properly

**Screenshots**
![image](https://user-images.githubusercontent.com/22997240/57427493-c41a2800-7241-11e9-9e7c-6355b37d7e70.png)

**Additional context**
RC: text-anchor style should be reversed in case of RTL context
![image](https://user-images.githubusercontent.com/22997240/57427618-4276ca00-7242-11e9-8878-24bbc9d55f5a.png)

**Comment by jmeijer-jupe** [comment] 2019-05-20 12:53
Duplicate of issue 509: https://github.com/swimlane/ngx-charts/issues/509

**Closed** 2019-05-20 12:56 UTC
Labels: Bug, Duplicate
