### ISSUE TITLE
Pass custom data to display in tooltip in treemap chart

### ISSUE THREAD

**Issue by MuruganLR** [swimlane/ngx-charts#781] opened 2018-03-22 11:28 UTC
Hi, I am using tree map chart in my project. I was struggling in display custom data in tooltip.
Can you please help to resolve this? 
If there is any example please share it.

**Comment by marjan-georgiev** [comment] 2018-04-08 20:44
Closing, as it is duplicate of #553. Let's continue the discussion there please.

**Closed by marjan-georgiev** 2018-04-08 20:44 UTC
