### ISSUE TITLE
Pie chart legend not drawn (if the slice is small)

### ISSUE THREAD

**Issue by drakir** [swimlane/ngx-charts#1130] opened 2019-03-15 13:17 UTC
**I'm submitting a ...**  (check one with "x")

- [ x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
In a pie chart, if the slice is quite small, estimated around 1% of the total value, the legend is not drawn.

**Expected behavior**
I expect the legend to be drawn for every slice.

**Reproduction of the problem**

Check this plunker:
https://plnkr.co/edit/5TcmnvgzoTbd1TdDCSwo?p=preview
Try a larger number for the slice that does not have a legend.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x
Tried 10.0.0 and 10.1.0. Same problem

* **Angular version:** x.x.x
Any

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android 
All
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by darshanrampatel** [comment] 2019-03-20 11:55
I can see the legend in your example, but it's the **tooltips** that don't appear to be working:

![image](https://user-images.githubusercontent.com/14162899/54682493-fbecd500-4b06-11e9-920e-1e0b64763876.png)

**Comment by drakir** [comment] 2019-03-20 13:16
@darshanrampatel 
Yes you are correct, its actually the same request as #880 now when you mentioned it.

I do understand that the default behaviour would work this way, like for instance when you have lots of small slices in the graph, but in our case we would like to override this behaviour since we have very few slices where one or two are small. The drawn tooltip wouldn't overlap in our cases.

**Comment by marjan-georgiev** [comment] 2019-05-20 12:58
Closing this as a duplicate of #880.

**Closed by marjan-georgiev** 2019-05-20 12:58 UTC
