### ISSUE TITLE
Warning and Error in AOT compilation

### ISSUE THREAD

**Issue by dombr7035** [swimlane/ngx-charts#507] opened 2017-08-09 10:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
It's OK in JIT mode.
In AOT mode the application works fine in browser but I have warning and error messages during building, like this:

For example the first warning:
`WARNING in ./~/@swimlane/ngx-charts/release/ngx-charts.module.js
Cannot find source file '../build/ngx-charts.module.ts': Error: Can't resolve '../build/ngx-charts.module.ts' in '/Users/guest/Prive/DevAngular/proto-chartev3-angular/node_modules/@swimlane/ngx-charts/release'
 @ ./aot/src/app/app.module.ngfactory.ts 60:0-70
 @ ./src/main-aot.ts
 @ multi ./src/main-aot`

For example the first error:
`ERROR in ./~/@swimlane/ngx-charts/release/common/base-chart.component.css
    Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
        at Object.module.exports.pitch (/Users/guest/Prive/DevAngular/proto-chartev3-angular/node_modules/extract-text-webpack-plugin/loader.js:27:9)`

**Expected behavior**
No warnings or errors on building.

**Please tell us about your environment:**

* **ngx-charts version**:6.0.1

* **Angular version:** 4.2.4

* **Webpack version:** 2.2.1

**Comment by marjan-georgiev** [comment] 2018-05-02 14:31
AoT should be working fine on latest version. Here is a demo project with clean install of latest angular cli and ngx-charts: https://github.com/marjan-georgiev/Angular-CLI-ngx-charts-Demo

If you're still having issues, it is likely due to local configuration. If you still think there is a bug, please open a new issue with a link to a repository where the error can be reproduced. Closing this.

**Closed by marjan-georgiev** 2018-05-02 14:31 UTC
