### ISSUE TITLE
Resize bug on Resize

### ISSUE THREAD

**Issue by MichaelLazarevic** [swimlane/ngx-charts#755] opened 2018-03-08 12:20 UTC
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When I resize my window / tab in any way, the bars within the chart (Using Vertical Bar) grow in size. This prompts the entire chart to grow in size, and no matter how many times I do it this never stops leading to an insane size.

**Expected behavior**
They would retain the same size or shrink to fit the window. Tested with and without flex-shrink, yet this seems to have 0 effect.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, https and Visual Studio Code.

* **ngx-charts version:** x.x.x
Latest Version

* **Angular version:** 2.x.x
Angular 5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Angular 5s

**Comment by marjan-georgiev** [comment] 2018-03-08 14:12
This happens if the container around the charts has a padding. Is that the case?
If so, just add another div around the chart with 0 padding and width and height set to 100%.

**Comment by MichaelLazarevic** [comment] 2018-03-08 14:58
No padding, eventually worked out that the ever increasing size was caused by a missing [View] tag, though I am having issues getting the chart to properly fit into a <mat-card> property, as it often overlaps the sides (No padding / border / margin, and adding them doesn't fix it)

**Comment by marjan-georgiev** [comment] 2018-03-08 15:00
Can you create a stackblitz where this can be reproduced? If you set the view input, the chart no longer resizes to fit the container.

**Comment by MichaelLazarevic** [comment] 2018-03-08 15:02
If I don't set the view input and initialise the chart without it, then put the chart inside a container (<mat-card>) it will pro-actively increase the size of the bars (Vertical Bar Chart) causing growth for the entire chart, without limits unless maximums are not set.

At the moment, with a View in place, this does not occur but any resizes cause the chart itself to clip over the edges of a <mat-card>, and while it does increase the size of the card the chart itself always remains bigger.

**Comment by marjan-georgiev** [comment] 2018-03-08 15:08
Try adding a height style to the chart's parent container. If the container does not have a height set, its height will default to 0, so the chart does not resize to fit in that case.

**Comment by MichaelLazarevic** [comment] 2018-03-08 15:19
I did, I used height / weight and even applied min/max. It would stop growing bigger after hitting a max but would always overlap with the card.

**Comment by marjan-georgiev** [comment] 2018-03-08 15:21
Not sure what else it could be. If you can create a stackblitz I could take a look.

**Comment by JoshSchoen** [comment] 2018-03-08 15:40
@MichaelLazarevic just a though and not sure what your markup looks like but if you have a number of nested div or other containers it's possible you are overriding some style props unintentionally. I would test it with a simple implementation outside your current implementation if you haven't already using @marjan-georgiev directions and see if that works, then refactor accordingly to simplify your markup. I personally have seen a couple of hard to debug issues like this using flexbox and it was due to nesting and style overrides.

**Comment by MichaelLazarevic** [comment] 2018-03-08 15:43
Literally just have 1 graph in a single <mat-card> as I'm only testing how it works.

**Comment by marjan-georgiev** [comment] 2018-04-08 21:07
Closing this for the time being. If you are able to reproduce and provide us with an example in stackblitz I would be happy to reopen.

**Closed by marjan-georgiev** 2018-04-08 21:07 UTC
Labels: Needs Demo

**Comment by sarora2073** [comment] 2019-06-25 15:54
fyi - experienced an issue where the chart keeps resizing (when there's a data change that would cause the chart to have to redraw). I was putting the chart in a mat-card element which I guess grows dynamically as well, but putting the chart in a div allowed it work responsively with flexbox without growing unexpectedly on each data change.

**Comment by rotobash** [comment] 2019-11-12 22:18
Hi, I'm also experiencing this issue as well. I have made a minimal stackblitz that reproduces the issue. If you keep toggling the minimize/maximize button on the browser (on Chrome at least) the graph continues to grow, it doesn't seem to happen in the editor window though. Hope this helps!

[Link to app](https://angular-9wpwaf.stackblitz.io)
[Link to editor](https://stackblitz.com/edit/angular-9wpwaf)

**Comment by evgenious** [comment] 2019-11-18 10:27
Experienced the same issue in our implementation, might be some miscalculation on window resize, couldn't identify the bug so far.

**Comment by beckyarauz** [comment] 2019-11-20 10:44
this is still an issue, whenever I resize the window the bar graph just keeps growing!, and if I set a max-height in the graph, the legends below overflow the container of the graph.

**Comment by Crocsx** [comment] 2020-05-07 07:10
I am using bootstrap and maybe I set up incorrectly, but I have the problem too. I made an example here :

https://swimlane-stacked-horizontal-bar-chart.stackblitz.io

**Comment by archit324** [comment] 2020-05-08 05:16
There is some issue with the library as height is getting dynamically calculated but it is getting increased always whenever the size of the window is changed.

**Comment by RuneHanssens** [comment] 2020-08-12 09:57
Removing padding from the parent container fixed the issue for me.

**Comment by andrea-mauro** [comment] 2021-01-01 10:11
I'd need this feature too, in order to handle translations for the label. My proposal would be to allow the user to define a `legendEntryTemplate` as a child of the component, similarly to the `tooltipTemplate`. The template would accept `color` and `label` as parameters. I've forked the project and implemented the feature. If contributions are accepted on this, I could submit a pull request.
Following there's an example of usage and a screenshot of the result

```html
      <ngx-charts-pie-chart
        *ngIf="chartType === 'pie-chart'"
        class="chart-container"
        [view]="view"
        [scheme]="colorScheme"
        [results]="single"
        [animations]="animations"
        [legend]="showLegend"
        [legendTitle]="legendTitle"
        [legendPosition]="legendPosition"
        [explodeSlices]="explodeSlices"
        [labels]="showLabels"
        [doughnut]="doughnut"
        [arcWidth]="arcWidth"
        (legendLabelClick)="onLegendLabelClick($event)"
        [gradient]="gradient"
        [tooltipDisabled]="tooltipDisabled"
        [tooltipText]="pieTooltipText"
        (dblclick)="dblclick($event)"
        (select)="select($event)"
        (activate)="activate($event)"
        (deactivate)="deactivate($event)"
      >
        <ng-template #legendEntryTemplate let-color="color" let-label="label">
          <span [style]="'color: ' + color">{{label}}</span>
        </ng-template>
      </ngx-charts-pie-chart>
```

![image](https://user-images.githubusercontent.com/54074100/103436950-a02f0580-4c21-11eb-8575-16793acd6de1.png)

**Comment by jjamaral** [comment] 2021-09-30 16:19
+1

**Comment by annndrey** [comment] 2023-08-10 22:44
Putting the chart inside a wrapper div container and setting it's max-height & min-height solves the issue. 

Example:

`<mat-card-content>
          <div class="chart-wrapper">
            <ngx-charts-pie-chart
              [scheme]="colorScheme"
              [results]="gender_data"
              [gradient]="gradient"
              [legend]="showLegend"
              [animations]="animations"
              [labels]="showLabels"
              [doughnut]="isDoughnut"
              [arcWidth]="arcWidth"
              (select)="onSelect($event)"
              (activate)="onActivate($event)"
              (deactivate)="onDeactivate($event)"
              >
            </ngx-charts-pie-chart>
            </div>
        </mat-card-content>`

and in css:

`
.chart-wrapper {
    max-height: 40vh;
    min-height: 40vh;
}
`
