### ISSUE TITLE
ng build -aot breaks because of missing file ./tooltip.scss in release folder

### ISSUE THREAD

**Issue by stephanrauh** [swimlane/ngx-charts#129] opened 2016-12-09 13:51 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Running `ng build -aot` runs into problems because the tooltip directive declares an import of a file that exists in the `src` folder, but not in the `release` folder of the node module.

Copying the file from `.../node_modules/ng2d3/src/common/tooltip/tooltip.scss` to `.../node_modules/ng2d3/release/common/tooltip/tooltip.scss` temporarily solves the problem, but we can't do that in our automatic build chain.

```
ERROR in ./~/ng2d3/release/common/tooltip/tooltip.directive.js
Module not found: Error: Can't resolve './tooltip.scss' in '/Users/stephan/git/ExploringAngular/ng2d3charts/node_modules/ng2d3/release/common/tooltip'
 @ ./~/ng2d3/release/common/tooltip/tooltip.directive.js 12:0-25
 @ ./src/~/ng2d3/release/common/area-tooltip.component.ngfactory.ts
 @ ./src/~/ng2d3/release/line-chart/line-chart.component.ngfactory.ts
 @ ./src/app/linechart/linechart.component.ngfactory.ts
 @ ./src/app/app.component.ngfactory.ts
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi main
```

**Expected behavior**
ng build -aot terminates without problems :).

**Reproduction of the problem**
I've prepared a demo repository for you. Simply follow these steps:
```
git clone https://github.com/stephanrauh/ng2d3-demo.git
cd ng2d3-demo
npm install
ng build -aot
```

**What is the motivation / use case for changing the behavior?**
We can't use ng2d3 until the problem is solved, not even in development (because of the strict settings of Jenkins).

**Please tell us about your environment:**
Angular CLI v1.0.0-beta.2

* **ng2d3 version:** 1.9.0

* **Angular version:** 2.2.3

* **Browser:** 
This is not a browser problem.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1

**Comment by stephanrauh** [comment] 2016-12-09 13:52
The file causing the error is TooltipDirective, line 9:

```typescript
import { TooltipContentComponent } from './tooltip.component';
import { TooltipService } from './tooltip.service';
import './tooltip.scss';  // <<<<<<
export declare class TooltipDirective implements OnDestroy {
```

**Comment by alyahmedaly** [comment] 2016-12-22 10:58
any update on this

**Comment by marjan-georgiev** [comment] 2016-12-23 00:17
Pushed a fix for the tooltip.scss issue. Please let me know if everything works now.

**Comment by alyahmedaly** [comment] 2016-12-23 06:26
Yes it works!

**Comment by jonnysamps** [comment] 2017-01-06 21:22
Looks like this hasn't been published yet? What version can I expect this to be in?

**Comment by amcdnl** [comment] 2017-01-07 14:43
Sorry, holidays. Next week first thing!

**Comment by stephanrauh** [comment] 2017-01-07 20:24
I'm not sure - but I was under the impression that AOT works with the new version ngx-charts 3.0.3.

**Comment by mariuspruski** [comment] 2017-01-30 14:02
I still have this error under ngx-charts 4.0.1:
> ERROR in ENOENT: no such file or directory, open 'D:\Projects\ngtest\node_modules\@swimlane\ngx-charts\release\common\tooltip\tooltip.component.scss'

**Comment by lvanngo** [comment] 2017-01-30 16:31
This is also blocking me.  Does anyone know what the cause is?

**Comment by ssleptsov** [comment] 2017-01-31 13:22
Version 4.0.3 already have fixed that.

**Closed** 2017-01-31 15:13 UTC
Labels: Bug, Effort: Easy, Priority: High

**Comment by lvanngo** [comment] 2017-01-31 17:34
Thanks!
