### ISSUE TITLE
ERROR TypeError: n.rgb is not a function

### ISSUE THREAD

**Issue by randymay-insclix** [swimlane/ngx-charts#1291] opened 2019-10-29 16:55 UTC
**Describe the bug**
I have added several bar graphs to my Angular 8.2.12 application, and they work beautifully.  I recently added a heat map, and I am seeing the following error:

main.663f7eda36bb1abc50f2.js:1 ERROR TypeError: n.rgb is not a function
    at MI (main.663f7eda36bb1abc50f2.js:1)
    at AI (main.663f7eda36bb1abc50f2.js:1)
    at t (main.663f7eda36bb1abc50f2.js:1)
    at eR (main.663f7eda36bb1abc50f2.js:1)
    at jR (main.663f7eda36bb1abc50f2.js:1)
    at n.c [as scale] (main.663f7eda36bb1abc50f2.js:1)
    at n.getColor (main.663f7eda36bb1abc50f2.js:1)
    at main.663f7eda36bb1abc50f2.js:1
    at Array.map (<anonymous>)
    at main.663f7eda36bb1abc50f2.js:1

**ngx-charts version**
I am using nix-charts 12.0.1, and this problem is visible in both Safari, and Chrome.

**Comment by Michel73** [comment] 2019-11-05 12:26
I have the same problem. As a workaround I use the angular-cli option `--optimization=false`.

**Comment by Michel73** [comment] 2019-11-05 15:14
I solved my problem. Updated version of `@angular-devkit/build-angular` from `0.801.0` to `0.803.17`.

**Comment by NikitaPooja** [comment] 2019-11-11 04:16
Hello,

I got the error when I have reload the page. In  "@angular-devkit/build-angular": "^0.10.6" version 

Error TypeError: t.rgb is not a function

**Comment by rajitha1998** [comment] 2019-11-13 13:24
Thanks @Michel73  Updated version of @angular-devkit/build-angular solved the issue

**Comment by antoinedepardailhantc** [comment] 2019-11-14 18:25
Having the same issue with latest angular packages. None of the solutions above worked.

Project works fine in npm start / jit mode, but not int AOT.

**Comment by taimoor99** [comment] 2019-12-03 12:12
I think the issue is related to d3 packages. I solve this kind of problem with this solution.
https://github.com/swimlane/ngx-charts/issues/1305#issuecomment-557113006

**Comment by marjan-georgiev** [comment] 2019-12-11 00:52
The d3 packages have been updated in v 13.0.0. Closing this as fixed. Please open a new issue if you still see a problem.

**Closed by marjan-georgiev** 2019-12-11 00:52 UTC
Labels: Bug

**Comment by GoodHow** [comment] 2021-04-21 03:12
Same as the issue: https://github.com/d3/d3-color/issues/68
