### ISSUE TITLE
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'

### ISSUE THREAD

**Issue by ramuda** [swimlane/ngx-charts#539] opened 2017-09-01 07:21 UTC
Angular version 5.x

**Comment by HitomiTenshi** [comment] 2017-09-04 09:23
Already fixed and merged (see PR #535), though not included in a release yet.

**Comment by marjan-georgiev** [comment] 2017-09-05 22:00
This will come with the next release.

**Closed** 2017-09-05 22:00 UTC

**Comment by Taha-Di-Nero** [comment] 2017-10-02 07:12
This is blocking me to upgrade to Angular 5, Can you please release a Patch ??

**Comment by HitomiTenshi** [comment] 2017-10-02 07:39
You can use my custom build while there's no official release. My custom build includes PRs #535, #555 and #359.

Install with:

```
npm install github:HitomiTenshi/ngx-charts#custom-build-next --save
```

Branch custom-build-next is using ngx-charts v6.0.2.

Please keep an eye out for the status of your desired PR and use the original ngx-charts library once it is in any way included in it.

**Comment by Taha-Di-Nero** [comment] 2017-10-02 07:54
@HitomiTenshi  thanks for u r quick reply.

**Comment by Taha-Di-Nero** [comment] 2017-10-02 10:19
@HitomiTenshi  used u r custom build and evrything work well under jit compiler.
Building with --prod that mean AOT I encountered a blocking error : 

> Uncaught TypeError: Cannot read property 'call' of undefined
    at e (main.87e7c34237d682911659.bundle.js:1)
    at Object../src/common/tooltip/injection.service.ts (main.87e7c34237d682911659.bundle.js:1)
    at e (main.87e7c34237d682911659.bundle.js:1)
    at Object../src/common/tooltip/tooltip.service.ts (main.87e7c34237d682911659.bundle.js:1)
    at e (main.87e7c34237d682911659.bundle.js:1)
    at Object../src/common/tooltip/tooltip.directive.ts (main.87e7c34237d682911659.bundle.js:1)
    at e (main.87e7c34237d682911659.bundle.js:1)
    at Object../src/common/tooltip/tooltip.module.ts (main.87e7c34237d682911659.bundle.js:1)
    at e (main.87e7c34237d682911659.bundle.js:1)
    at Object../src/common/tooltip/index.ts (main.87e7c34237d682911659.bundle.js:1)

Did u test u r PRs  in production mode ??

**Comment by HitomiTenshi** [comment] 2017-10-02 18:35
Yes I have tested all my PRs as I use them in production myself. The latest `angular 5.0.0-rc.0` isn't working with AOT on my end as well, I should've said that this morning. They did some breaking changes since `5.0.0-beta.7`.

I'm using `angular 5.0.0-beta.6`, which is the last working version. I didn't have time yet to investigate the root cause of those errors. I bet there are more changes than PR #535 needed to support angular version beyond `5.0.0-beta.6`.

Sorry for the late response.

**Comment by Taha-Di-Nero** [comment] 2017-10-03 06:32
@HitomiTenshi don't worry I did downgrade to 4.4.4 will wait until Angular release a stable version.
Thanks a lot

**Comment by Taha-Di-Nero** [comment] 2017-11-02 09:55
Just upgrade today to Angular 5.0.0 and everything is working as expected.  (version 6.1.0)

**Comment by Anoop-Goudar** [comment] 2017-11-08 14:11
By replacing ngOutletContext to ngTemplateOutletContext in all files, it worked for me.

**Comment by joselee** [comment] 2017-11-20 07:27
Thanks @Anoop-Goudar ! your answer worked for me Angular-5.0.2
