### ISSUE TITLE
Line Chart on Firefox can't select the points

### ISSUE THREAD

**Issue by macvag** [swimlane/ngx-charts#534] opened 2017-08-29 07:52 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
![screenshot from 2017-08-29 10-43-29](https://user-images.githubusercontent.com/7754679/29810284-009064e2-8ca8-11e7-85c6-b234573f60d9.png)

**Reproduction of the problem**
To reproduce the bug you can from Firefox:

1. go to https://swimlane.gitbooks.io/ngx-charts/content/charts/line-chart.html 
2. add more points to data.ts
3. try to select a point 

* **Browser:** [ Firefox 55.0.2 (64-bit) ]

**Comment by RafikSM** [comment] 2017-08-30 11:36
I have the same problem here on firefox

**Comment by tobigit** [comment] 2017-09-07 13:59
I have already created an issue about that: https://github.com/swimlane/ngx-charts/issues/469

**Comment by marjan-georgiev** [comment] 2017-09-15 12:15
Closing as this is a duplicate of #469

**Closed by marjan-georgiev** 2017-09-15 12:15 UTC
