### ISSUE TITLE
line chart show wrong colors

### ISSUE THREAD

**Issue by henbarlevi** [swimlane/ngx-charts#465] opened 2017-07-05 13:16 UTC
**Current behavior**
line chart randomaly show wrong colors than what it defiend to show (sometimes different lines show 
the same color):
![image](https://user-images.githubusercontent.com/21140848/27865824-c07c4cd0-619c-11e7-9647-1c51776a24f3.png)
## im talking about the line chart in the left bottom side
my line chart get the object 
colorScheme = {
        domain: ['#5AA454', '#C7B42C', '#A10A28'] //GREEN ,AMBER ,RED
    };
in the [scheme] property

**Expected behavior**
line chart always show the correct colors

**Reproduction of the problem**

**Please tell us about your environment:**

* **ngx-charts version:**
"@swimlane/ngx-charts": "^5.3.1",
* **Angular version:*
 "@angular/animations": "^4.1.2",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",

* **Browser:** all 

* **Language:** all

**Comment by marjan-georgiev** [comment] 2017-07-05 13:19
This is a duplicate of #453, so I'll close it.

**Closed by marjan-georgiev** 2017-07-05 13:19 UTC
