### ISSUE TITLE
Cannot find module "." when running universal server

### ISSUE THREAD

**Issue by Zhefraudmarc** [swimlane/ngx-charts#855] opened 2018-05-25 22:59 UTC
When I followed the [Angular Universal: server-side rendering](https://angular.io/guide/universal) tutorial to start the universal server, I met the error:
```
Error: Cannot find module "."
    at webpackMissingModule (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:164237:82)
    at Object.. (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:164237:160)
    at __webpack_require__ (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:164176:30)
    at Object../node_modules/@swimlane/ngx-charts/release/common/circle-series.component.js (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:168816:59)
    at __webpack_require__ (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:164176:30)
    at Object../node_modules/@swimlane/ngx-charts/release/common/circle-series.component.ngfactory.js (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:169083:10)
    at __webpack_require__ (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:164176:30)
    at Object../node_modules/@swimlane/ngx-charts/release/line-chart/line-chart.component.ngfactory.js (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:192065:10)
    at __webpack_require__ (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:164176:30)
    at Object../src/app/domains/inspector/dmarc-panel/dmarc-panel.component.ngfactory.js (/home/zhezhu/Documents/fm-frontend-jobs/dist/server.js:208172:11)
```
I tried to start it without webpack, then there would be another error with ngx-charts:

```
/home/zhezhu/Documents/fm-frontend-jobs/node_modules/@swimlane/ngx-charts/release/line-chart/line-series.component.js:10
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```
and I don't know why.

Thanks for your help.

**Comment by takumi-hoppler** [comment] 2018-05-30 06:20
I'm also having the same problem.

ngx-charts version: 7.3.0
Angular version: 5.0

**Comment by tawn33y** [comment] 2018-06-06 09:43
Found a fix after being stuck with this error for 3 days: 🙂 

In your project root, open these two files:
i) 'node_modules/@swimlane/ngx-charts/release/common/circle-series.component.d.ts'
ii) 'node_modules/@swimlane/ngx-charts/release/common/circle-series.component.js'

In each file, replace the following line of code
```ts
import { ColorHelper } from '.'
````
with
```ts
import { ColorHelper } from '../common/color.helper'
````
You should be good to go. Just save and build your project.

### Additional Note
Afterwards, when you try to build the project you might experience the following error: "Prerendering failed because of error: ReferenceError: MouseEvent is not defined".

To solve this, install regexp-replace-loader:
```sh
npm i regexp-replace-loader --save-dev
```

Then in './webpack.server.config.js', update rules as follows:
```js
module.exports = {
  ...
  module: {
    rules: [
      {
        test: /\.ts$/,
        loader: 'ts-loader'
      },
      {
        test: /\.(ts|js)$/,
        loader: 'regexp-replace-loader',
        options: {
          match: {
            pattern:'\\[(Mouse|Keyboard)Event\\]',
            flags:'g'
          },
          replaceWith:'[]'
        }
      }
    ]
  }
  ...
};
```

### Future Considerations
This error occurs because of a simple mistake in the source code of the ngx-charts project. It is my askance, kindly, if the core team could replace the lines in the two files above with my proposed fixes, as this would ensure no future errors for developers using Angular Universal.

Happy coding! Cheers! 😎

**Comment by marjan-georgiev** [comment] 2018-07-17 14:50
Merged the PR. This will be in the next release. Thanks for the contribution everyone!

**Closed** 2018-07-17 14:53 UTC

**Comment by zvirja** [comment] 2018-07-17 15:01
@marjan-georgiev Please ensure to merge #919 and #921 before the next release, as otherwise SSR is broken 😖

**Comment by marjan-georgiev** [comment] 2018-07-17 15:05
@zvirja awesome contribution, thank you! Merged the other 2 issues.

Any chance you can create a demo repository with ngx-charts workin in SSR and share it? Would be very helpful to everyone.

**Comment by zvirja** [comment] 2018-07-17 15:17
@marjan-georgiev I'll try my best, but I'm a newbie at front end. I'm working with the already configured solution and am not sure can configure the similar one from scratch. However, if I have free time I could give it a try.

Could you please share your plans regarding the next release timeline? I wish to consume the changes and make it finally work after spending 2 days on the fix 😊 

I've just built the latest master and everything works fine.

**Comment by marjan-georgiev** [comment] 2018-07-17 15:23
I'll try to cut a release today.

**Comment by zvirja** [comment] 2018-07-17 15:24
@marjan-georgiev Would be super awesome, thanks! :heart_eyes:

**Comment by marjan-georgiev** [comment] 2018-07-17 23:37
Released in 9.0.0.

**Comment by zvirja** [comment] 2018-07-18 08:55
@marjan-georgiev Many thanks for the quick cooperation - really impressive!

BTW, it seems you forgot to push a git tag 😊

**Comment by Pibomeister** [comment] 2018-09-03 01:30
Hi guys I'm experiencing this with the vertical bar chart component when trying to do SSR. I'm running version 9.0.0 of Ngx charts and Angular version 6.1.6. Any help would be appreciated

**Comment by yanivamrami** [comment] 2018-09-23 09:45
@Pibomeister  did you find a solution? I am getting the same problem running Angular 6.0.2 with ngx-charts 9.0.0

**Comment by Pibomeister** [comment] 2018-09-25 21:16
@yanivamrami Yes as a matter of fact I did. The issue is with how ngx charts is packaged, currently node doesn't support the current packaging. To fix this I installed **Babbel** as a dev dependency and added the following scripts to my package.json:

- "compile_@swimlane_ngx-charts": "babel node_modules/@swimlane/ngx-charts -d node_modules/@swimlane/ngx-charts --presets es2015"

- "postinstall": "npm run compile_@swimlane_ngx-charts"

So whenever I run npm install, ngx charts is automatically compiled into a compatible format. I have no issues runnning this with **Angular 6.1.6**,  **@nguniversal/express-engine 6.1.0** and **@nguniversal/common 6.1.0**.

Hope I was of help!

**Comment by robinComa** [comment] 2018-10-21 21:19
Thanks @Pibomeister  !!!

**Comment by hallysonh** [comment] 2019-05-24 01:35
This problem is back. I am trying to make a app-shell using the angular cli generator and builder, guided by [this link](https://angular.io/guide/app-shell)

Error: `SyntaxError: Unexpected token {` in `@swimlane\ngx-charts\release\common\axes\x-axis.component.js:10`

```
"@angular/animations": "^7.2.15",
"@angular/platform-browser-dynamic": "^7.2.15",
"@swimlane/ngx-charts": "^11.1.0",
"@angular/cli": "7.3.9",
```

![CWINDOWSsystem32cmd exe_3](https://user-images.githubusercontent.com/3520994/58296662-f0d64f80-7daa-11e9-887a-cacad4ecabe8.jpg)
