### ISSUE TITLE
Material beta 12 incompatibility - Unable to resolve animation metadata node #undefined

### ISSUE THREAD

**Issue by chogainz** [swimlane/ngx-charts#607] opened 2017-10-20 13:34 UTC
CURRENT VERSIONS

    "@angular/animations": "4.4.6",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/material": "2.0.0-beta.12",

Updated to material beta 12
Throws this error
Error: Unable to resolve animation metadata node #undefined

![ngx-charts-error](https://user-images.githubusercontent.com/14838235/31823279-857a318c-b5a3-11e7-923b-ed2659ae4d50.PNG)

**Comment by marjan-georgiev** [comment] 2017-10-23 15:25
Is this caused by ngx-charts?

**Comment by skyboys22** [comment] 2018-01-03 23:07
i'm getting same error

**Comment by morrisond91** [comment] 2018-12-07 16:47
Did you ever get to the bottom of this?

**Comment by mpeguero** [comment] 2019-03-19 17:47
I had this error and I change the definitions of the animation functions and worked fine.

`/****BEFORE *****/
export function moveIn(){
    return trigger('moveIn',[
        state('void',style({position:'fixed',width:'100%'})),
        state('*' ,style({position:'fixed', width:'100%'})),
        transition(':enter',[
            style({opacity:'0',transform:'translateX(100%'}),
            animate('.6s ease-in-out',style({opacity:'1',transform:'translateX(0)'}))
        ]),
        transition(':leave',[
            style({opacity:'1',transform:'translateX(-100%'}),
            animate('.6s ease-in-out',style({opacity:'0',transform:'translateX(-200px)'}))
        ]),        
    ])
}


/*** AFTER ****/
export let moveIn = trigger('moveIn',[
        state('void',style({position:'fixed',width:'100%'})),
        state('*' ,style({position:'fixed', width:'100%'})),
        transition(':enter',[
            style({opacity:'0',transform:'translateX(100%'}),
            animate('.6s ease-in-out',style({opacity:'1',transform:'translateX(0)'}))
        ]),
        transition(':leave',[
            style({opacity:'1',transform:'translateX(-100%'}),
            animate('.6s ease-in-out',style({opacity:'0',transform:'translateX(-200px)'}))
        ]),        
    
	]);`

**Comment by marjan-georgiev** [comment] 2019-05-23 12:40
Closing this. If anyone still has this issue, please open a new ticket with a stackblitz where it can be reproduced.

**Closed by marjan-georgiev** 2019-05-23 12:40 UTC
Labels: Need More Info, Needs Demo
