### ISSUE TITLE
Regression bug: [scheme]-colors not working on line chart

### ISSUE THREAD

**Issue by sueess** [swimlane/ngx-charts#453] opened 2017-06-23 12:07 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
In the new version (5.3.1) the (color-)scheme gets applied wrong to the line chart (multiple times same color; different colors for point, labels and lines):
![new](https://user-images.githubusercontent.com/6587992/27481443-e45eea7e-581c-11e7-8314-9b70a495ddb5.png)

```
    colorScheme = {
        domain: ['#5eb4e7', '#43596c', '#88cac1', '#ffab91']
    };
```

**Expected behavior**
Should work like before (5.2.1):
![old](https://user-images.githubusercontent.com/6587992/27481454-f0adfe0a-581c-11e7-9b39-5629494af4ca.png)

**Comment by marjan-georgiev** [comment] 2017-06-23 17:43
I can't reproduce this locally, nor in the demo. Can you please post a plunkr where this is reproducible?

**Comment by sueess** [comment] 2017-06-26 05:46
https://plnkr.co/edit/UzgtrHbLy1qaG4qB5Jiq?p=preview

**Comment by MarkRyanDev** [comment] 2017-07-24 22:11
I am seeing a similar issue where setting up customColors is not applying properly.

**Comment by marjan-georgiev** [comment] 2017-07-25 15:48
Fixed, it will be in the next release.

**Closed by marjan-georgiev** 2017-07-25 15:48 UTC
Labels: Needs Demo
