### ISSUE TITLE
Allow users to associate arbitrary user data with points, lines, bars, slices, bubbles, etc

### ISSUE THREAD

**Issue by DonaldAlan** [swimlane/ngx-charts#790] opened 2018-04-03 22:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```
I want to be able to attach arbitrary *user data* to the bubbles of a bubble-chart and I want that user data to be returned in a select event that fires when the user clicks on the bubble.  But ngx-charts doesn't seem to let me do this directly.  The `results` object that I pass contains fields `name`, `x`, `y`,  and `r`.       I made a typescript class that contains those fields and also (for testing) my own `userData` field and I would like my object (with `userData`) to be returned to me as an OUTPUT for a click event.  But when I examine the object that's associated with the event (`$event`),  I see `{ name: -110.976, value: 42.762, series: "" }`. I was expecting `name`, `x`, `y`,  `r`, and (maybe) `userData`.  

I could build a map from name/value/series triples to my userData. But multiple userData objects may map to the same triple.

Allowing users to associate arbitrary user data with points/bars/lines/slices/bubbles, etc. would add power.  JavaFX does this in its charts.

**Comment by marjan-georgiev** [comment] 2018-04-08 20:10
This is a duplicate of #506. Let's continue the discussion there please.

**Closed by marjan-georgiev** 2018-04-08 20:10 UTC
